import { useMemo, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useRecoilState } from 'recoil'
import { authState, registerIndexState, youtubeState } from '../state/auth'
import styles from '../styles/Home.module.css'
import { Modal } from '../components/Modal'

const Home: NextPage = () => {
  const router = useRouter()
  const [openModal, setOpenModal] = useState(false)
  const [auth] = useRecoilState(authState)
  const [youtubeInfo] = useRecoilState(youtubeState)
  const [registerIndex] = useRecoilState(registerIndexState)

  const registerYouTubeInfo = useMemo(() => {
    return registerIndex === undefined ? undefined : youtubeInfo.at(registerIndex)
  }, [registerIndex, youtubeInfo])

  const onClose = () => {
    setOpenModal(false)
  }
  const onClick = () => {
    setOpenModal(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Google OAuth and YouTube Channel ID Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Modal open={openModal} onClose={onClose} />

        {auth.email && auth.email !== '' && registerYouTubeInfo !== undefined ? (
          <div>
            <p>Register Email: {auth.email}</p>
            <p>YouTube Channel ID: {registerYouTubeInfo.channelId}</p>
            <p>YouTube Title: {registerYouTubeInfo.title}</p>
            <p>YouTube Description: {registerYouTubeInfo.description}</p>
            <p>YouTube View Count: {registerYouTubeInfo.viewCount}</p>
            <p>YouTube Video Count: {registerYouTubeInfo.videoCount}</p>
            <p>YouTube Keywords: {registerYouTubeInfo.keywords}</p>
            <button onClick={() => router.push('/')}>Log Out</button>
          </div>
        ) : (
          <div>
            <button onClick={onClick}>View Channel Info</button>
          </div>
        )}
      </main>
    </div>
  )
}

export default Home
